name: shelfmate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  get: ^4.7.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/
