// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcbxU6bxTf6cWloT7Cq4o72xAI69OGQ7o',
    appId: '1:342275214248:ios:790c27b81425a89a90eb9d',
    messagingSenderId: '342275214248',
    projectId: 'shelfmate-d370c',
    storageBucket: 'shelfmate-d370c.firebasestorage.app',
    iosBundleId: 'com.example.shelfmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbPy2_OgAp1lhfRUmhHjKZNPcumD6bx2o',
    appId: '1:342275214248:web:1f0a11f0a883312590eb9d',
    messagingSenderId: '342275214248',
    projectId: 'shelfmate-d370c',
    authDomain: 'shelfmate-d370c.firebaseapp.com',
    storageBucket: 'shelfmate-d370c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbPy2_OgAp1lhfRUmhHjKZNPcumD6bx2o',
    appId: '1:342275214248:web:1f0a11f0a883312590eb9d',
    messagingSenderId: '342275214248',
    projectId: 'shelfmate-d370c',
    authDomain: 'shelfmate-d370c.firebaseapp.com',
    storageBucket: 'shelfmate-d370c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcbxU6bxTf6cWloT7Cq4o72xAI69OGQ7o',
    appId: '1:342275214248:ios:790c27b81425a89a90eb9d',
    messagingSenderId: '342275214248',
    projectId: 'shelfmate-d370c',
    storageBucket: 'shelfmate-d370c.firebasestorage.app',
    iosBundleId: 'com.example.shelfmate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDCi5kd-oCCzSen-LTO--RY-1_q18DIw',
    appId: '1:342275214248:android:b09603f2d3c028e690eb9d',
    messagingSenderId: '342275214248',
    projectId: 'shelfmate-d370c',
    storageBucket: 'shelfmate-d370c.firebasestorage.app',
  );

}